name: cd
on:
  release:
   types:
     - published
jobs:
  dockerhub:
    env:
      USERNAME: belcebus
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build hasher
        run: docker image build --file hasher/Dockerfile --tag index.docker.io/${USERNAME}/santander-dockercoins:$( basename ${GITHUB_REF} )-hasher hasher/
      - name: build rng
        run: docker image build --file rng/Dockerfile --tag index.docker.io/${USERNAME}/santander-dockercoins:$( basename ${GITHUB_REF} )-rng rng/
      - name: build webui
        run: docker image build --file webui/Dockerfile --tag index.docker.io/${USERNAME}/santander-dockercoins:$( basename ${GITHUB_REF} )-webui webui/
      - name: build worker
        run: docker image build --file worker/Dockerfile --tag index.docker.io/${USERNAME}/santander-dockercoins:$( basename ${GITHUB_REF} )-worker worker/
      - name: docker login
        run: | 
          docker login -u ${USERNAME} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push index.docker.io/${USERNAME}/santander-dockercoins:${GITHUB_REF}-hasher
          docker push index.docker.io/${USERNAME}/santander-dockercoins:${GITHUB_REF}-rng
          docker push index.docker.io/${USERNAME}/santander-dockercoins:${GITHUB_REF}-webui
          docker push index.docker.io/${USERNAME}/santander-dockercoins:${GITHUB_REF}-worker
          
        
