name: ci
on:
  push:
    branches:
      - 202106
jobs:
  dockerfile:
    env:
      USERNAME: belcebus
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build hasher
        run: docker image build --file hasher/Dockerfile --tag index.docker.io/${USERNAME}/santander-dockercoins:test-hasher hasher/
      - name: build rng
        run: docker image build --file rng/Dockerfile --tag index.docker.io/belcebus/santander-dockercoins:test-rng rng/
      - name: build webui
        run: docker image build --file webui/Dockerfile --tag index.docker.io/belcebus/santander-dockercoins:test-webui webui/
      - name: build worker
        run: docker image build --file worker/Dockerfile --tag index.docker.io/belcebus/santander-dockercoins:test-worker worker/
      - name: network for hasher
        run: docker network create hasher-network
      - name: network for redis
        run: docker network create redis-network
      - name: network for rng
        run: docker network create rng-network
      - name: volume for redis
        run: docker volume create redis-volume
      - name: run redis
        run: docker container run --detach --entrypoint docker-entrypoint.sh --name redis --network redis-network --rm --volume redis-volume:/data --workdir /data redis:6.2.4-alpine3.13@sha256:1f2550814d7288982a5b321089e3fa3a47ae86ac7c59f02409c8210b8408530d redis-server
      - name: run hasher
        run: docker container run --detach --entrypoint irb --name hasher --network hasher-network --rm --volume ${PWD}/hasher/hasher.rb:/src/hasher.rb:ro --workdir /src/ index.docker.io/belcebus/santander-dockercoins:test-hasher hasher.rb
      - name: run rng
        run: docker container run --detach --entrypoint python3 --name rng --network rng-network --rm --volume ${PWD}/rng/rng.py:/src/rng.py:ro --workdir /src/ index.docker.io/belcebus/santander-dockercoins:test-rng rng.py
      - name: run webui
        run: docker container run --detach --entrypoint node  --name webui --network redis-network --rm --volume ${PWD}/webui/webui.js:/src/webui.js:ro --volume ${PWD}/webui/files:/src/files:ro --workdir /src/ index.docker.io/belcebus/santander-dockercoins:test-webui webui.js
      - name: run worker
        run: docker container run --detach --entrypoint python3 --name worker --network hasher-network --rm --volume ${PWD}/worker/worker.py:/src/worker.py:ro --workdir /src/ index.docker.io/belcebus/santander-dockercoins:test-worker worker.py
      - name: connecting network
        run: docker network connect redis-network worker
      - name: connecting network
        run: docker network connect rng-network worker
      - name: Cecking execution
        run: while true; do sleep 10 && docker container logs worker && docker container logs worker 2>&1 | grep "Coin found" && break; done
